SELECT
  MIN(smd_pct)    AS min_smd,
  AVG(smd_pct)    AS avg_smd,
  MAX(smd_pct)    AS max_smd,
  MIN(sub2_pct)   AS min_sub2,
  AVG(sub2_pct)   AS avg_sub2,
  MAX(sub2_pct)   AS max_sub2,
  MIN(sub3_pct)   AS min_sub3,
  AVG(sub3_pct)   AS avg_sub3,
  MAX(sub3_pct)   AS max_sub3,
  MIN(tob3_pct)   AS min_tob3,
  AVG(tob3_pct)   AS avg_tob3,
  MAX(tob3_pct)   AS max_tob3,
  MIN(medcont_pct)AS min_medcont,
  AVG(medcont_pct)AS avg_medcont,
  MAX(medcont_pct)AS max_medcont,
  MIN(imm2_pct)   AS min_imm2,
  AVG(imm2_pct)   AS avg_imm2,
  MAX(imm2_pct)   AS max_imm2,
  MIN(readm_rate) AS min_readm,
  AVG(readm_rate) AS avg_readm,
  MAX(readm_rate) AS max_readm
FROM `risk.cleaned_inpatientPsy`;